//! Local mirrors of the canic-orchestrated fleet's candid types.
//!
//! `canic_canister_children` is generated by canic, not this crate, so
//! these are hand-declared mirrors of its candid interface (verified
//! against a real canic project's generated `.did` files) rather than
//! shared types — the same pattern Task 8's `sql/transport.rs` uses for
//! icydb's own generated types.

use candid::{CandidType, Principal};
use serde::{Deserialize, Serialize};

#[derive(CandidType, Clone, Debug, Deserialize)]
pub struct CanisterInfo {
    pub pid: Principal,
    pub role: String,
    pub created_at: u64,
    pub module_hash: Option<Vec<u8>>,
    pub parent_pid: Option<Principal>,
}

#[derive(CandidType, Clone, Debug, Deserialize)]
pub struct CanicPage {
    pub total: u64,
    pub entries: Vec<CanisterInfo>,
}

#[derive(CandidType, Clone, Debug, Deserialize)]
pub struct PageRequest {
    pub offset: u64,
    pub limit: u64,
}

/// Canic's error is `record { code : ErrorCode; message : text }`. Only `message`
/// is declared here: candid skips unmatched record fields on decode, so this
/// deliberately avoids coupling to canic's large and evolving `ErrorCode` variant.
#[derive(CandidType, Clone, Debug, Deserialize)]
pub struct CanicError {
    pub message: String,
}

#[derive(Clone, Debug, Serialize)]
pub struct TreeNode {
    pub pid: String,
    pub role: String,
    pub children: Vec<TreeNode>,
}
