//! Maps icydb's numeric diagnostic codes to the names in its registry.
//!
//! icydb deliberately does not ship the names at runtime: `DiagnosticCode`'s
//! `Debug` renders the number, and the crate documents why — "the public Candid
//! `icydb::Error` stores this value as `nat16` so canister interfaces do not
//! retain rich diagnostic enum labels". So a canister can only ever tell this
//! app `E96`.
//!
//! Which leaves the reader holding a number. Naming it is most of the value:
//! `SQL_FEATURE_ORDER_BY_FIELD_NOT_ORDERABLE` can be searched in icydb's source
//! and issue tracker, and `96` cannot. This app hand-explains a handful of codes
//! with real remedies; this table covers the rest so an unexplained failure is
//! still identifiable.
//!
//! Generated from `icydb-diagnostic-code-{version}/src/registry.rs`, which is
//! the single table those codes are defined in. This app pins an exact icydb
//! version, so the table is valid for exactly that pin — see README, "Updating
//! the icydb version". `every_listed_code_is_still_known_to_icydb` fails if a
//! bump removes one; nothing can detect a *rename*, which is the residual risk
//! and the reason the code number is always shown alongside the name.

/// Every public diagnostic code in the pinned icydb's registry, ascending.
const CODES: &[(u16, &str)] = &[
    (1, "QUERY_VALIDATE"),
    (2, "QUERY_INTENT"),
    (3, "QUERY_PLAN"),
    (4, "QUERY_ACCESS_REQUIREMENT"),
    (5, "QUERY_UNORDERED_PAGINATION"),
    (6, "QUERY_INVALID_CONTINUATION_CURSOR"),
    (7, "QUERY_NOT_FOUND"),
    (8, "QUERY_NOT_UNIQUE"),
    (9, "QUERY_NUMERIC_OVERFLOW"),
    (10, "QUERY_NUMERIC_NOT_REPRESENTABLE"),
    (11, "QUERY_UNKNOWN_AGGREGATE_TARGET_FIELD"),
    (12, "QUERY_UNSUPPORTED_SQL_FEATURE"),
    (13, "QUERY_SQL_SURFACE_MISMATCH"),
    (14, "SCHEMA_DDL_ADMISSION"),
    (15, "STORE_NOT_FOUND"),
    (16, "STORE_CORRUPTION"),
    (17, "STORE_INVARIANT_VIOLATION"),
    (18, "RUNTIME_CORRUPTION"),
    (19, "RUNTIME_INCOMPATIBLE_PERSISTED_FORMAT"),
    (20, "RUNTIME_INVARIANT_VIOLATION"),
    (21, "RUNTIME_CONFLICT"),
    (22, "RUNTIME_NOT_FOUND"),
    (23, "RUNTIME_UNSUPPORTED"),
    (24, "RUNTIME_INTERNAL"),
    (25, "RUNTIME_BOUNDARY_SQL_SURFACE_CONTROLLER_REQUIRED"),
    (26, "RUNTIME_BOUNDARY_SCHEMA_SURFACE_CONTROLLER_REQUIRED"),
    (27, "RUNTIME_BOUNDARY_SQL_QUERY_NO_CONFIGURED_ENTITIES"),
    (28, "RUNTIME_BOUNDARY_SQL_QUERY_ENTITY_NOT_CONFIGURED"),
    (29, "RUNTIME_BOUNDARY_SQL_DDL_TARGET_REQUIRED"),
    (30, "RUNTIME_BOUNDARY_SQL_DDL_ENTITY_NOT_CONFIGURED"),
    (31, "RUNTIME_BOUNDARY_QUERY_RESPONSE_ROWS_REQUIRED"),
    (32, "RUNTIME_BOUNDARY_QUERY_RESPONSE_GROUPED_ROWS_REQUIRED"),
    (33, "RUNTIME_BOUNDARY_ROW_PROJECTION_FIELD_NOT_CONFIGURED"),
    (34, "SQL_FEATURE_AGGREGATE_FILTER_CLAUSE"),
    (35, "SQL_FEATURE_ALTER_STATEMENT_BEYOND_ALTER_TABLE"),
    (36, "SQL_FEATURE_ALTER_TABLE_ADD_COLUMN_DUPLICATE_DEFAULT"),
    (37, "SQL_FEATURE_ALTER_TABLE_ADD_COLUMN_MODIFIERS"),
    (38, "SQL_FEATURE_ALTER_TABLE_ADD_STATEMENT_BEYOND_ADD_COLUMN"),
    (39, "SQL_FEATURE_ALTER_TABLE_ALTER_COLUMN_DROP_UNSUPPORTED_ACTION"),
    (40, "SQL_FEATURE_ALTER_TABLE_ALTER_COLUMN_MODIFIERS"),
    (41, "SQL_FEATURE_ALTER_TABLE_ALTER_COLUMN_SET_UNSUPPORTED_ACTION"),
    (42, "SQL_FEATURE_ALTER_TABLE_ALTER_COLUMN_UNSUPPORTED_ACTION"),
    (43, "SQL_FEATURE_ALTER_TABLE_ALTER_STATEMENT_BEYOND_ALTER_COLUMN"),
    (44, "SQL_FEATURE_ALTER_TABLE_DROP_COLUMN_IF_EXISTS_SYNTAX"),
    (45, "SQL_FEATURE_ALTER_TABLE_DROP_COLUMN_MODIFIERS"),
    (46, "SQL_FEATURE_ALTER_TABLE_DROP_STATEMENT_BEYOND_DROP_COLUMN"),
    (47, "SQL_FEATURE_ALTER_TABLE_RENAME_COLUMN_MISSING_TO"),
    (48, "SQL_FEATURE_ALTER_TABLE_RENAME_COLUMN_MODIFIERS"),
    (49, "SQL_FEATURE_ALTER_TABLE_RENAME_STATEMENT_BEYOND_RENAME_COLUMN"),
    (50, "SQL_FEATURE_ALTER_TABLE_UNSUPPORTED_OPERATION"),
    (51, "SQL_FEATURE_COLUMN_ALIAS"),
    (52, "SQL_FEATURE_CREATE_INDEX_IF_NOT_EXISTS_SYNTAX"),
    (53, "SQL_FEATURE_CREATE_INDEX_KEY_ORDERING_MODIFIERS"),
    (54, "SQL_FEATURE_CREATE_INDEX_MODIFIERS"),
    (55, "SQL_FEATURE_CREATE_STATEMENT_BEYOND_CREATE_INDEX"),
    (56, "SQL_FEATURE_DESCRIBE_MODIFIER"),
    (57, "SQL_FEATURE_DDL_SCHEMA_VERSION_DUPLICATE_EXPECTED_CLAUSE"),
    (58, "SQL_FEATURE_DDL_SCHEMA_VERSION_DUPLICATE_SET_CLAUSE"),
    (59, "SQL_FEATURE_DROP_INDEX_MODIFIERS"),
    (60, "SQL_FEATURE_DROP_INDEX_IF_EXISTS_SYNTAX"),
    (61, "SQL_FEATURE_DROP_STATEMENT_BEYOND_DROP_INDEX"),
    (62, "SQL_FEATURE_EXPRESSION_INDEX_UNSUPPORTED_FUNCTION"),
    (63, "SQL_FEATURE_HAVING"),
    (64, "SQL_FEATURE_INSERT"),
    (65, "SQL_FEATURE_JOIN"),
    (66, "SQL_FEATURE_LIKE_PATTERN_BEYOND_TRAILING_PREFIX"),
    (67, "SQL_FEATURE_LOWER_FIELD_PREDICATE_UNSUPPORTED"),
    (68, "SQL_FEATURE_MULTI_STATEMENT_SQL"),
    (69, "SQL_FEATURE_NESTED_AGGREGATE_INPUT"),
    (70, "SQL_FEATURE_NESTED_PROJECTION_FUNCTION_IN_ARITHMETIC"),
    (71, "SQL_FEATURE_ORDER_BY_UNSUPPORTED_FORM"),
    (72, "SQL_FEATURE_OTHER"),
    (73, "SQL_FEATURE_PREDICATE_STARTS_WITH_FIRST_ARGUMENT"),
    (74, "SQL_FEATURE_QUOTED_IDENTIFIERS"),
    (75, "SQL_FEATURE_RETURNING_UNSUPPORTED_SHAPE"),
    (76, "SQL_FEATURE_SCALAR_FUNCTION_EXPRESSION_POSITION"),
    (77, "SQL_FEATURE_SCALE_TAKING_NUMERIC_FUNCTION_EXPRESSION_POSITION"),
    (78, "SQL_FEATURE_SEARCHED_CASE_GROUPED_ORDER_BY"),
    (79, "SQL_FEATURE_SHOW_COLUMNS_MODIFIERS"),
    (80, "SQL_FEATURE_SHOW_ENTITIES_MODIFIERS"),
    (81, "SQL_FEATURE_SHOW_INDEXES_MODIFIERS"),
    (82, "SQL_FEATURE_SHOW_MEMORY_MODIFIERS"),
    (83, "SQL_FEATURE_SHOW_STORES_MODIFIERS"),
    (84, "SQL_FEATURE_SHOW_UNSUPPORTED_COMMAND"),
    (85, "SQL_FEATURE_SIMPLE_CASE_EXPRESSION"),
    (86, "SQL_FEATURE_STANDALONE_LITERAL_PROJECTION_ITEM"),
    (87, "SQL_FEATURE_SUPPORTED_GROUPED_ORDER_BY_EXPRESSION_FAMILY"),
    (88, "SQL_FEATURE_SUPPORTED_ORDER_BY_EXPRESSION_FAMILY"),
    (89, "SQL_FEATURE_UNION_INTERSECT_EXCEPT"),
    (90, "SQL_FEATURE_UNSUPPORTED_FUNCTION_NAMESPACE"),
    (91, "SQL_FEATURE_UPDATE"),
    (92, "SQL_FEATURE_UPPER_FIELD_PREDICATE_UNSUPPORTED"),
    (93, "SQL_FEATURE_WINDOW_FUNCTION"),
    (94, "SQL_FEATURE_WITH"),
    (95, "SQL_FEATURE_NUMERIC_SCALE_FUNCTION_ARGUMENTS"),
    (96, "SQL_FEATURE_ORDER_BY_FIELD_NOT_ORDERABLE"),
    (97, "SQL_SURFACE_QUERY_REJECTS_INSERT"),
    (98, "SQL_SURFACE_QUERY_REJECTS_UPDATE"),
    (99, "SQL_SURFACE_QUERY_REJECTS_DELETE"),
    (100, "SQL_SURFACE_MUTATION_REJECTS_SELECT"),
    (101, "SQL_SURFACE_MUTATION_REJECTS_EXPLAIN"),
    (102, "SQL_SURFACE_MUTATION_REJECTS_DESCRIBE"),
    (103, "SQL_SURFACE_MUTATION_REJECTS_SHOW_INDEXES"),
    (104, "SQL_SURFACE_MUTATION_REJECTS_SHOW_COLUMNS"),
    (105, "SQL_SURFACE_MUTATION_REJECTS_SHOW_ENTITIES"),
    (106, "SQL_SURFACE_MUTATION_REJECTS_SHOW_STORES"),
    (107, "SQL_SURFACE_MUTATION_REJECTS_SHOW_MEMORY"),
    (108, "SCHEMA_DDL_MISSING_EXPECTED_SCHEMA_VERSION"),
    (109, "SCHEMA_DDL_MISSING_NEXT_SCHEMA_VERSION"),
    (110, "SCHEMA_DDL_STALE_EXPECTED_SCHEMA_VERSION"),
    (111, "SCHEMA_DDL_INVALID_EXPECTED_SCHEMA_VERSION"),
    (112, "SCHEMA_DDL_INVALID_NEXT_SCHEMA_VERSION"),
    (113, "SCHEMA_DDL_ACCEPTED_SCHEMA_CHANGE_WITHOUT_VERSION_BUMP"),
    (114, "SCHEMA_DDL_EMPTY_VERSION_BUMP"),
    (115, "SCHEMA_DDL_VERSION_GAP"),
    (116, "SCHEMA_DDL_VERSION_ROLLBACK"),
    (117, "SCHEMA_DDL_FINGERPRINT_METHOD_MISMATCH"),
    (118, "SCHEMA_DDL_UNSUPPORTED_TRANSITION_CLASS"),
    (119, "SCHEMA_DDL_PHYSICAL_RUNNER_MISSING"),
    (120, "SCHEMA_DDL_VALIDATION_FAILED"),
    (121, "SCHEMA_DDL_PUBLICATION_RACE_LOST"),
    (122, "SCHEMA_DDL_INVALID_ADD_COLUMN_DEFAULT"),
    (123, "SCHEMA_DDL_INVALID_ALTER_COLUMN_DEFAULT"),
    (124, "SCHEMA_DDL_GENERATED_INDEX_DROP_REJECTED"),
    (125, "SCHEMA_DDL_REWRITE_REQUIRES_MIGRATION"),
    (126, "SCHEMA_DDL_GENERATED_FIELD_DEFAULT_CHANGE_REJECTED"),
    (127, "SCHEMA_DDL_GENERATED_FIELD_NULLABILITY_CHANGE_REJECTED"),
    (128, "SQL_FEATURE_SHOW_CONSTRAINTS_MODIFIERS"),
    (129, "QUERY_SQL_WRITE_BOUNDARY"),
    (130, "SQL_WRITE_PRIMARY_KEY_LITERAL_SHAPE"),
    (131, "SQL_WRITE_PRIMARY_KEY_LITERAL_INCOMPATIBLE"),
    (132, "SQL_WRITE_MISSING_PRIMARY_KEY"),
    (133, "SQL_WRITE_MISSING_REQUIRED_FIELDS"),
    (134, "SQL_WRITE_EXPLICIT_MANAGED_FIELD"),
    (135, "SQL_WRITE_EXPLICIT_GENERATED_FIELD"),
    (136, "SQL_WRITE_INSERT_SELECT_REQUIRES_SCALAR"),
    (137, "SQL_WRITE_INSERT_SELECT_AGGREGATE_PROJECTION"),
    (138, "SQL_WRITE_INSERT_SELECT_WIDTH_MISMATCH"),
    (139, "SQL_WRITE_UPDATE_PRIMARY_KEY_MUTATION"),
    (140, "SQL_WRITE_INVALID_FIELD_LITERAL"),
    (141, "SQL_WRITE_UNKNOWN_RETURNING_FIELD"),
    (142, "SQL_WRITE_DUPLICATE_RETURNING_FIELD"),
    (143, "SQL_WRITE_UPDATE_MISSING_WHERE_PREDICATE"),
    (144, "SQL_WRITE_ORDER_BY_UNSUPPORTED_SHAPE"),
    (145, "QUERY_UNSUPPORTED_PROJECTION"),
    (146, "QUERY_PROJECTION_NUMERIC_LITERAL_REQUIRED"),
    (147, "QUERY_PROJECTION_NUMERIC_SCALE_ARGUMENTS"),
    (148, "QUERY_PROJECTION_NESTED_FIELD_PATH_PREVIEW"),
    (149, "QUERY_PROJECTION_CASE_CONDITION_BOOLEAN_REQUIRED"),
    (150, "QUERY_PROJECTION_NUMERIC_INPUT_REQUIRED"),
    (151, "QUERY_PROJECTION_TEXT_OR_BLOB_INPUT_REQUIRED"),
    (152, "QUERY_PROJECTION_TEXT_INPUT_REQUIRED"),
    (153, "QUERY_PROJECTION_TEXT_OR_NULL_ARGUMENT_REQUIRED"),
    (154, "QUERY_PROJECTION_INTEGER_OR_NULL_ARGUMENT_REQUIRED"),
    (155, "QUERY_PROJECTION_UNARY_OPERAND_INCOMPATIBLE"),
    (156, "QUERY_PROJECTION_BINARY_OPERANDS_INCOMPATIBLE"),
    (157, "QUERY_RESULT_SHAPE_MISMATCH"),
    (158, "QUERY_RESULT_EXPECTED_ROWS"),
    (159, "QUERY_RESULT_EXPECTED_GROUPED"),
    (160, "SQL_LOWERING_ENTITY_MISMATCH"),
    (161, "SQL_LOWERING_SELECT_PROJECTION_SHAPE"),
    (162, "SQL_LOWERING_SELECT_DISTINCT"),
    (163, "SQL_LOWERING_DISTINCT_ORDER_BY_PROJECTION"),
    (164, "SQL_LOWERING_GLOBAL_AGGREGATE_PROJECTION"),
    (165, "SQL_LOWERING_GLOBAL_AGGREGATE_GROUP_BY"),
    (166, "SQL_LOWERING_SELECT_GROUP_BY_SHAPE"),
    (167, "SQL_LOWERING_GROUPED_PROJECTION_EXPLICIT_LIST_REQUIRED"),
    (168, "SQL_LOWERING_GROUPED_PROJECTION_AGGREGATE_REQUIRED"),
    (169, "SQL_LOWERING_GROUPED_PROJECTION_NON_GROUP_FIELD"),
    (170, "SQL_LOWERING_GROUPED_PROJECTION_SCALAR_AFTER_AGGREGATE"),
    (171, "SQL_LOWERING_HAVING_REQUIRES_GROUP_BY"),
    (172, "SQL_LOWERING_SELECT_HAVING_SHAPE"),
    (173, "SQL_LOWERING_AGGREGATE_INPUT_EXPRESSIONS"),
    (174, "SQL_LOWERING_WHERE_EXPRESSION_SHAPE"),
    (175, "SQL_LOWERING_PARAMETER_PLACEMENT"),
    (176, "SQL_LOWERING_SQL_DDL_EXECUTION_UNSUPPORTED"),
    (177, "SQL_WRITE_RETURNING_RESPONSE_TOO_LARGE"),
    (178, "SQL_WRITE_RETURNING_ROWS_TOO_MANY"),
    (179, "RUNTIME_BOUNDARY_SQL_INTROSPECTION_DISABLED"),
    (180, "SQL_WRITE_STAGED_ROWS_TOO_MANY"),
    (181, "QUERY_READ_ADMISSION"),
    (182, "QUERY_READ_PUBLIC_REQUIRES_LIMIT"),
    (183, "QUERY_READ_PUBLIC_REQUIRES_INDEX"),
    (184, "QUERY_READ_UNBOUNDED_FULL_SCAN_REJECTED"),
    (185, "QUERY_READ_SORT_REQUIRES_MATERIALIZATION"),
    (186, "QUERY_READ_GROUPED_QUERY_REQUIRES_LIMITS"),
    (187, "QUERY_READ_GROUPED_QUERY_EXCEEDS_BUDGET"),
    (188, "QUERY_READ_DIAGNOSTIC_LANE_DOES_NOT_EXECUTE"),
    (189, "QUERY_READ_RETURNED_ROW_BOUND_EXCEEDS_POLICY"),
    (190, "QUERY_READ_PRIMARY_KEY_INPUT_EXCEEDS_POLICY"),
    (191, "SCHEMA_DDL_ROW_LAYOUT_VERSION_EXHAUSTED"),
    (192, "SCHEMA_DDL_TRANSITION_BUDGET_EXCEEDED"),
    (193, "SQL_WRITE_INSERT_DEFAULT_REQUIRED_FIELD"),
    (194, "SQL_WRITE_UPDATE_DEFAULT_REQUIRED_FIELD"),
    (195, "SQL_WRITE_UPDATE_DEFAULT_DATABASE_OWNED_FIELD"),
    (196, "RUNTIME_BOUNDARY_MUTATION_REQUIRED_FIELD_MISSING"),
    (197, "RUNTIME_BOUNDARY_PERSISTED_ROW_LAYOUT_OUTSIDE_ACCEPTED_WINDOW"),
    (198, "RUNTIME_BOUNDARY_PERSISTED_ROW_SLOT_COUNT_MISMATCH"),
    (199, "RUNTIME_BOUNDARY_GENERATED_FIELD_AFTER_DDL_FIELD"),
    (200, "SQL_SURFACE_MUTATION_REQUIRES_EXPLICIT_UPDATE_INTENT"),
    (201, "SQL_WRITE_EXACT_UPDATE_ASSERTION_REQUIRED"),
    (202, "SQL_WRITE_EXACT_UPDATE_ASSERTION_TOO_HIGH"),
    (203, "SQL_WRITE_EXACT_UPDATE_AFFECTED_ROWS_EXCEEDED"),
    (204, "SQL_WRITE_EXACT_UPDATE_WINDOW_UNSUPPORTED"),
    (205, "SQL_WRITE_EXACT_UPDATE_SCAN_BUDGET_EXCEEDED"),
    (206, "SQL_WRITE_RESUMABLE_UPDATE_WINDOW_UNSUPPORTED"),
    (207, "SQL_WRITE_RESUMABLE_UPDATE_RETURNING_UNSUPPORTED"),
    (208, "SQL_WRITE_RESUMABLE_UPDATE_REQUIRES_JOURNALED_STORE"),
    (209, "SQL_WRITE_RESUMABLE_UPDATE_ASSIGNED_FIELD_HAS_GLOBAL_CONSTRAINT"),
    (210, "SQL_WRITE_RESUMABLE_UPDATE_SCOPE_DEPENDS_ON_ASSIGNED_FIELD"),
    (211, "SQL_WRITE_RESUMABLE_UPDATE_SCOPE_DEPENDENCY_UNKNOWN"),
    (212, "SQL_WRITE_RESUMABLE_UPDATE_CONTINUATION_MALFORMED"),
    (213, "SQL_WRITE_RESUMABLE_UPDATE_CONTINUATION_TARGET_MISMATCH"),
    (214, "SQL_WRITE_RESUMABLE_UPDATE_CONTINUATION_SCHEMA_MISMATCH"),
    (215, "SQL_WRITE_RESUMABLE_UPDATE_CONTINUATION_SCOPE_MISMATCH"),
    (216, "SQL_WRITE_RESUMABLE_UPDATE_CONTINUATION_PATCH_MISMATCH"),
    (217, "SQL_WRITE_RESUMABLE_UPDATE_CONTINUATION_BATCH_POLICY_MISMATCH"),
    (218, "SQL_WRITE_RESUMABLE_UPDATE_SINGLE_ROW_RESOURCE_EXCEEDED"),
    (219, "SQL_WRITE_RESUMABLE_UPDATE_MANAGED_FIELD_HAS_GLOBAL_CONSTRAINT"),
    (220, "SQL_WRITE_RESUMABLE_UPDATE_CONTINUATION_OPERATION_MISMATCH"),
    (221, "RUNTIME_BOUNDARY_JOURNAL_MUTATION_REVISION_EXHAUSTED"),
    (222, "SQL_SURFACE_MUTATION_REJECTS_SHOW_CONSTRAINTS"),
    (223, "RUNTIME_BOUNDARY_CONSTRAINT_VIOLATION"),
    (224, "RUNTIME_BOUNDARY_ACCEPTED_ROW_CONSTRAINT_PROGRAM_CORRUPT"),
    (225, "RUNTIME_BOUNDARY_CONSTRAINT_ACTIVATION_WRITE_BLOCKED"),
    (226, "SQL_FEATURE_ALTER_TABLE_ADD_CONSTRAINT_BEYOND_CHECK"),
    (227, "SQL_FEATURE_ALTER_TABLE_ADD_CONSTRAINT_MODIFIERS"),
    (228, "SQL_FEATURE_ALTER_TABLE_DROP_CONSTRAINT_IF_EXISTS_SYNTAX"),
    (229, "SQL_FEATURE_ALTER_TABLE_DROP_CONSTRAINT_MODIFIERS"),
    (230, "SQL_FEATURE_ALTER_TABLE_VALIDATE_BEYOND_CONSTRAINT"),
    (231, "SQL_FEATURE_ALTER_TABLE_VALIDATE_CONSTRAINT_MODIFIERS"),
    (232, "RUNTIME_BOUNDARY_GENERATED_CONSTRAINT_ACTIVATION_STALE"),
    (233, "RUNTIME_BOUNDARY_MUTATION_MANAGED_TIMESTAMP_REGRESSION"),
    (234, "RUNTIME_BOUNDARY_MUTATION_DATABASE_OWNED_FIELD_EXPLICIT"),
    (235, "RUNTIME_BOUNDARY_MUTATION_BATCH_EMPTY"),
    (236, "RUNTIME_BOUNDARY_MUTATION_BATCH_TOO_MANY_ITEMS"),
    (237, "RUNTIME_BOUNDARY_MUTATION_BATCH_STAGED_BYTES_EXCEEDED"),
    (238, "RUNTIME_BOUNDARY_MUTATION_BATCH_RESULT_BYTES_EXCEEDED"),
    (239, "RUNTIME_BOUNDARY_MUTATION_BATCH_ENTITY_MISMATCH"),
    (240, "RUNTIME_BOUNDARY_MUTATION_BATCH_DUPLICATE_KEY"),
];

/// The registry name for `code`, or `None` if this build's table does not list
/// it — which for a canister running a newer icydb than this explorer is the
/// expected answer, not an error.
#[must_use]
pub fn diagnostic_name(code: u16) -> Option<&'static str> {
    CODES
        .binary_search_by_key(&code, |(raw, _)| *raw)
        .ok()
        .map(|index| CODES[index].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_the_codes_this_app_has_actually_seen() {
        // All four observed live against toko or the fixture.
        assert_eq!(diagnostic_name(3), Some("QUERY_PLAN"));
        assert_eq!(diagnostic_name(5), Some("QUERY_UNORDERED_PAGINATION"));
        assert_eq!(
            diagnostic_name(25),
            Some("RUNTIME_BOUNDARY_SQL_SURFACE_CONTROLLER_REQUIRED")
        );
        assert_eq!(
            diagnostic_name(96),
            Some("SQL_FEATURE_ORDER_BY_FIELD_NOT_ORDERABLE")
        );
    }

    #[test]
    fn an_unlisted_code_is_none_rather_than_a_wrong_name() {
        assert_eq!(diagnostic_name(60_000), None);
    }

    /// The table is generated from a pinned version, so it can drift. This
    /// catches a code being removed by a bump. It cannot catch a rename — the
    /// runtime API exposes no names to compare against — which is why the
    /// number is always rendered next to the name.
    #[test]
    fn every_listed_code_is_still_known_to_icydb() {
        let unknown: Vec<u16> = CODES
            .iter()
            .filter(|(raw, _)| icydb::ErrorCode::known(*raw).is_none())
            .map(|(raw, _)| *raw)
            .collect();
        assert!(
            unknown.is_empty(),
            "codes no longer in icydb's registry — regenerate this table: {unknown:?}"
        );
    }

    /// `diagnostic_name` binary-searches, so the table must stay sorted.
    #[test]
    fn the_table_is_sorted_and_unique() {
        let mut previous = None;
        for (raw, _) in CODES {
            if let Some(last) = previous {
                assert!(*raw > last, "table is out of order at {raw}");
            }
            previous = Some(*raw);
        }
        assert_eq!(CODES.len(), 240);
    }
}
